"""
Reconcile MCP Server
====================

DESIGN INTENT
-------------
This is the *standardized boundary* between the reasoning agents and the
financial data. In production, the SQLite backend below is swapped for the
company's ERP behind this exact same MCP interface — the agents never change.
That substitutability is why MCP is organic here, not a checkbox.

The server exposes seven tools (read, safe-write, gated-write, append-only).
Privilege enforcement and human-confirmation do NOT live here — they live in
the ADK guardrail/confirmation layer that wraps these tools. This server's job
is correct, well-typed data primitives with money handled as integer cents.

Run:  python -m mcp_server.server   (stdio transport, for ADK MCPToolset)
"""

from __future__ import annotations

import sqlite3
import json
from datetime import datetime, timezone
from difflib import SequenceMatcher
from pathlib import Path

from mcp.server.fastmcp import FastMCP

DB_PATH = Path(__file__).parent.parent / "data" / "reconcile.db"

mcp = FastMCP("reconcile")


def _con() -> sqlite3.Connection:
    """Open a row-dict connection. Read tools use this; the DB is generated by
    data/generate.py and must exist before the server starts."""
    if not DB_PATH.exists():
        raise FileNotFoundError(
            f"{DB_PATH} not found. Run `python data/generate.py` first."
        )
    con = sqlite3.connect(DB_PATH)
    con.row_factory = sqlite3.Row
    return con


def _rows(query: str, args: tuple = ()) -> list[dict]:
    con = _con()
    try:
        return [dict(r) for r in con.execute(query, args).fetchall()]
    finally:
        con.close()


# ---------------------------------------------------------------------------
# READ TOOLS
# ---------------------------------------------------------------------------
@mcp.tool()
def get_ledger_entries(period: str) -> list[dict]:
    """Return all GENERAL LEDGER entries for a fiscal period (e.g. '2026-05').

    Each entry includes txn_id, txn_date, vendor, amount_cents, account_code,
    memo, and invoice_ref. Amounts are integer CENTS — never floats — so the
    matching agent can compare exactly without rounding error."""
    return _rows(
        "SELECT * FROM transactions WHERE source='ledger' AND period=?",
        (period,),
    )


@mcp.tool()
def fetch_bank_statement(period: str) -> list[dict]:
    """Return all BANK STATEMENT transactions for the period. Same schema as
    ledger entries. The matching agent reconciles these against ledger +
    invoices in a 3-way match."""
    return _rows(
        "SELECT * FROM transactions WHERE source='bank' AND period=?",
        (period,),
    )


@mcp.tool()
def fetch_invoices(period: str) -> list[dict]:
    """Return all VENDOR INVOICES for the period. The invoice_ref field links
    an invoice to its ledger/bank payments and is the key the duplicate-payment
    check relies on."""
    return _rows(
        "SELECT * FROM transactions WHERE source='invoice' AND period=?",
        (period,),
    )


@mcp.tool()
def lookup_vendor(name: str) -> dict:
    """Fuzzy-resolve a possibly-variant vendor name to the vendor master.

    Returns the best matching master record plus a `confidence` score in
    [0,1]. Resolves e.g. 'ACME Corporation Inc.' -> V001 ('Acme Corp.').
    Uses difflib ratio on case-folded names; a deterministic, dependency-free
    matcher so the demo is reproducible. A confidence < 0.6 should be treated
    by the caller as "no confident match"."""
    candidates = _rows("SELECT * FROM vendors")
    target = name.casefold().strip()

    def score(master_name: str) -> float:
        return SequenceMatcher(None, target, master_name.casefold()).ratio()

    best = max(candidates, key=lambda v: score(v["name"]))
    return {
        "vendor_id": best["vendor_id"],
        "name": best["name"],
        "category": best["category"],
        "query": name,
        "confidence": round(score(best["name"]), 3),
    }


# ---------------------------------------------------------------------------
# SAFE WRITE — flag only (never moves money)
# ---------------------------------------------------------------------------
@mcp.tool()
def flag_transaction(txn_id: str, reason: str, actor: str = "AnomalyAgent") -> dict:
    """Flag a transaction for manual audit/review.

    Args:
        txn_id: The ID of the transaction to flag.
        reason: Human-readable explanation of why the transaction is flagged.
        actor: The agent/system triggering the flag. Defaults to "AnomalyAgent".

    DESIGN INTENT & REUSE INTEGRITY:
    ----------------------------------
    The MCP server is decoupled from the agent orchestration layer. To ensure
    correct attribution in the append-only audit log, the caller should pass
    the `actor` name. The client-side security guardrail intercepts this tool call
    and dynamically injects the calling agent's name (from tool_context.agent_name)
    into the `actor` parameter.

    The default is set to "AnomalyAgent" to ensure backward compatibility and avoid
    breaking agent LLM calls where the LLM does not explicitly pass the actor argument.
    """
    _write_audit(actor, "flag_transaction",
                 json.dumps({"txn_id": txn_id, "reason": reason}))
    return {"status": "flagged", "txn_id": txn_id, "reason": reason}


# ---------------------------------------------------------------------------
# GATED WRITE — the only money-moving tool. The ADK confirmation layer wraps
# this; the server primitive itself records the posting + audit entry. It must
# never be exposed to an agent without the confirmation wrapper.
# ---------------------------------------------------------------------------
@mcp.tool()
def post_adjustment(entry_txn_id: str, amount_cents: int, reason: str) -> dict:
    """Post a CORRECTING adjustment against a transaction. GATED: in the ADK
    layer this requires explicit human confirmation before it can execute.

    Records an adjustment row in the audit log with the originating txn, the
    signed amount in cents (negative reverses a payment), and the human-
    readable reason. Returns the posted record for the narrative summary."""
    detail = json.dumps({
        "entry_txn_id": entry_txn_id,
        "amount_cents": amount_cents,
        "reason": reason,
    })
    _write_audit("CloseOrchestrator", "post_adjustment", detail)
    return {"status": "posted", "entry_txn_id": entry_txn_id,
            "amount_cents": amount_cents, "reason": reason}


# ---------------------------------------------------------------------------
# APPEND-ONLY AUDIT LOG
# ---------------------------------------------------------------------------
@mcp.tool()
def write_audit_log(actor: str, action: str, detail: str) -> dict:
    """Append an immutable record to the audit trail (actor, action, detail,
    UTC timestamp). APPEND-ONLY: there is intentionally no update/delete tool,
    so the close is fully reconstructable. Used by the NarrativeAgent."""
    _write_audit(actor, action, detail)
    return {"status": "logged", "actor": actor, "action": action}


def _write_audit(actor: str, action: str, detail: str) -> None:
    """Internal append helper. PII masking is applied in the ADK guardrail
    BEFORE detail reaches here, so by this point `detail` is already redacted."""
    con = _con()
    try:
        con.execute(
            "INSERT INTO audit_log(ts, actor, action, detail) VALUES (?,?,?,?)",
            (datetime.now(timezone.utc).isoformat(), actor, action, detail),
        )
        con.commit()
    finally:
        con.close()


if __name__ == "__main__":
    # stdio transport — ADK's MCPToolset launches this as a subprocess.
    mcp.run()
